export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";

export const SUBMENU_OPEN = "SUBMENU_OPEN";
export const SUBMENU_CLOSE = "SUBMENU_CLOSE";

export const CHANNEL_OPEN = "CHANNEL_OPEN";
export const CHANNEL_CLOSE = "CHANNEL_CLOSE";

export const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const GET_SINGLE_PRODUCT_BEGIN = "GET_SINGLE_PRODUCT_BEGIN";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR";

export const GET_PRICELISTS_BEGIN = "GET_PRICELISTS_BEGIN";
export const GET_PRICELISTS_SUCCESS = "GET_PRICELISTS_SUCCESS";
export const GET_PRICELISTS_ERROR = "GET_PRICELISTS_ERROR";

export const GET_SLIDER_BEGIN = "GET_SLIDER_BEGIN";
export const GET_SLIDER_SUCCESS = "GET_SLIDER_SUCCESS";
export const GET_SLIDER_ERROR = "GET_SLIDER_ERROR";

export const GET_CARRENTALS_BEGIN = "GET_CARRENTALS_BEGIN";
export const GET_CARRENTALS_SUCCESS = "GET_CARRENTALS_SUCCESS";
export const GET_CARRENTALS_ERROR = "GET_CARRENTALS_ERROR";

export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const SET_GRIDVIEW = "SET_GRIDVIEW";
export const SET_LISTVIEW = "SET_LISTVIEW";
export const UPDATE_SORT = "UPDATE_SORT";
export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const TOGGLE_CART_ITEM_AMOUNT = "TOGGLE_CART_ITEM_AMOUNT";
export const CLEAR_CART = "CLEAR_CART";
export const COUNT_CART_TOTALS = "COUNT_CART_TOTALS";
